# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - testdockerdrew

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://testdockerdrew.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_b129fe99f82b4d52ad48b9fcc91f3e2a }}
        password: ${{ secrets.AzureAppService_ContainerPassword_b99f3574f41842d9ab0305bb59b9732a }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: testdockerdrew.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_b129fe99f82b4d52ad48b9fcc91f3e2a }}/gen-ml:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'testdockerdrew'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_aa4197428f4a46329469e66d134e455e }}
        images: 'testdockerdrew.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_b129fe99f82b4d52ad48b9fcc91f3e2a }}/gen-ml:${{ github.sha }}'